
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird tinybird_introduction - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
    jobs:
      cd:  # deploy changes to workspace 'tinybird_introduction'
        uses: tinybirdco/ci/.github/workflows/cd.yml@v3.1.0
        with:
          data_project_dir: .
        secrets:
          tb_admin_token: ${{ secrets.TB_TINYBIRD_INTRODUCTION_ADMIN_TOKEN }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://ui.tinybird.co
